config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :projects, except: [:delete] do
    resources :tasks, only: [:create, :show, :index]
  end

  get 'static_pages/about'

  root 'static_pages#home'
end

app/models/project.rb
require "pry"
class Project < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3 }
  belongs_to :owner, foreign_key: 'user_id', class_name: 'User'
  has_many :tasks

  has_many :project_collaborations
  has_many :collaborators, through: :project_collaborations, source: :user

  after_save :add_user_as_admin
  after_save :set_collaborator_role_to_user

  def is_collaborator
    collaborators.map { |user| user.email }.join(', ')
  end

  def is_collaborator=(new_collaborators)
    self.collaborators = new_collaborators.split(', ').map { |email| User.find_by(email: email) }
  end

  def recent_tasks
    tasks.where(["updated_at > ?", 7.days.ago])
  end

  def recent_collaborators
    recent_additions = project_collaborations.where(["created_at > ?", 7.days.ago])
    recent_additions.map(&:user)
  end

  def recent_activity
    activity = recent_tasks + recent_collaborators
    activity.sort! { |a, b| a.created_at <=> b.created_at }.reverse!
  end

  private

  def add_user_as_admin
    if owner && !collaborators.include?(owner)
      ProjectCollaboration.create(project_id: self.id, user_id: owner.id, role: 0)
    end
  end

  def set_collaborator_role_to_user
    self.project_collaborations.where(role: nil).each do |x|
      x.role = 'user'
      x.save
    end
  end
end

app/models/project_collaboration.rb
class ProjectCollaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  enum role: [:admin, :user]
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates_presence_of :title

  belongs_to :project
  belongs_to :user

  def overdue?
    if date_due
      date_due < Date.today
    else
      false
    end
  end
end

app/models/user.rb
require 'pry'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :projects
  has_many :project_collaborations
  has_many :collaborations, through: :project_collaborations, source: :project

  def project_role(project)
    project_collaborations.where("user_id = ? AND project_id = ?", self.id, project.id).first
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.skip_confirmation!
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def after_sign_in_path_for(resource)
    projects_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.collaborations
    authorize @projects
  end

  def show
    @project = Project.find(params[:id])
    @task = Task.new
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = current_user.projects.build(project_params)
    authorize @project

    if @project.save
      flash[:notice] = "New project created."
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project

    if @project.update(project_params)
      flash[:notice] = "Project updated successfully."
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :is_collaborator)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks

    respond_to do |format|
      format.json { render json: @tasks }
    end
  end

  def show
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    # binding.pry
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @task }
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)

    if @task.save
      render 'create.js', layout: false
    end
  end

private

  def task_params
    params.require(:task).permit(:title, :date_due)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
require 'pry'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
  def display_recent_activity(item)
    if item.class == Task
      return "A new task was created: #{item.title}, Due date: #{item.date_due ? item.date_due : 'No due date'}"
    else
      return "A new collaborator was added: #{item.email}"
    end
  end

  def format_overdue_tasks(task)
    task.overdue? ? "overdue-item" : "normal"
  end

end

app/views/layouts/_footer.html.erb
  <hr>
  <footer>
    <p>© 2016 Company, Inc.</p>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bazaar</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <div class="navbar-form navbar-right">
      <% if user_signed_in? %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
        <%= link_to 'Project List', projects_path, class: 'btn btn-default' %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default' %>
        <%= link_to 'Sign in with Facebook', user_omniauth_authorize_path(:facebook), class: 'btn btn-default' %>
      <% end %>
      </div>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAssessmentBazaar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'shared/messages' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script> -->
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h3 class="field_with_errors">
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:
    </h3 class="field_with_errors">
    <ul class="field_with_errors">
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class"form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class"form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class"form-group">
    <%= f.label :is_collaborator, 'Search Users' %>
    <input type="text" id="username_email" data-emails="<%= User.order(:email).map(&:email) %>">
    <div id="add_to_list" class="btn btn-xs btn-default">Add user</div><br/>
    <%= f.text_area :is_collaborator, id: "collaborator_list" %>
  </div>
  <%= f.submit @project.new_record? ? 'Create Project' : 'Update Project', class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <div class="well clearfix">
    <div class="col-md-4">
      <strong><%= project.title %></strong>
    </div>
    <div class="col-md-4">
      <%= link_to 'View Project', project_path(project), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p class="lead"><%= @project.description %></p>
<div>
  <% if policy(@project).edit? %>
    <p><%= link_to 'Edit Project', edit_project_path(@project), class: 'btn btn-success' %></p>
  <% end %>
</div>
<div class="well">
  <h3>Latest Updates</h3>
  <% if @project.recent_activity.empty? %>
    <p class="no-activity">No recent activity here. Go ahead and get started!</p>
  <% else %>
    <ul>
      <% @project.recent_activity.each do |item| %>
        <li><%= display_recent_activity(item) %></li>
      <% end %>
    </ul>
  <% end %>

  <h3>Tasks</h3>
  <button id="task-toggle" class="btn btn-default">New Task</button>

  <div id="add-task" style="display:none;">
    <%= form_for [@project, @task], remote: true do |f| %>
    <% if @task.errors.any? %>
      <h3 class="field_with_errors">
        <%= pluralize(@task.errors.count, "error") %>
        prohibited this task from being saved:
      </h3 class="field_with_errors">
      <ul class="field_with_errors">
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :date_due %>
    <%= f.date_select :date_due, as: :date, start_year: Date.today.year,
                                end_year: Date.today.year + 10,
                                order: [:day,:month, :year] %>
    <%= f.submit 'Create Task', class: 'btn btn-sm btn-primary' %>
    <% end %>
  </div>

  <% if @project.tasks.empty? %>
    <p class="no-activity">No open tasks. Click above to create a new one!</p>
  <% else %>
    <ul id="task-list">
      <%= render partial: 'tasks/task', locals: { :project => @project } %>
    </ul>
  <% end %>

</div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Bazaar</h1>
    <p>On the way to Everest Basecamp is a town know as Bazaar. Thats what we are. A project management app that is not quite to Basecamp</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Unlimited Projects</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
    </div>
    <div class="col-md-4">
      <h2>Collaboration</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
    </div>
    <div class="col-md-4">
      <h2>Always Free</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
    </div>
  </div>

app/views/tasks/_task.html.erb
<% project.tasks.each do |task| %>
<li>
  <% if task.overdue? %>
  <span class="badge">Overdue</span>
  <% end %>
  <span class=<%= format_overdue_tasks(task) %>><%= link_to task.title, project_task_path(project, task) %> | <%= task.date_due %></span>
</li>
<% end %>

app/views/tasks/create.js.erb
$('#task_title').val("");
var $ul = $("#task-list");
$ul.html("<%= j(render('tasks/task', :project => @project)) %>");

app/views/tasks/show.html.erb
<h1 id="taskTitle"><%= @task.title %></h1>
<br>
<p id="taskDateDue"><%= @task.date_due %></p>

<%= link_to 'Back to project', project_path(@project), class: 'btn btn-default' %>
<button id="js-next-task" class="btn btn-success">Next Task</button>

<script>
  var taskArray;
  var index = 0;
  var projectId = <%= @task.project.id %>

  // GET request to retun array of project tasks IDs
  $.get("/projects/" + projectId + "/tasks.json", function(data) {
    var tasks = data["tasks"];
    taskArray = tasks.map(function(a) { return a.id; });
  }).done(function() {
    $("#js-next-task").on("click", function() {
      index++;
      var nextId = taskArray[index];

      // Get request to get JSON of each task
      $.get("/projects/" + projectId + "/tasks/" + nextId + ".json", function(data) {
        var task = data["task"];
        $("#taskTitle").text(task["title"]);
        $("#taskDateDue").text(task["date_due"]);
      });
    });
  })
</script>